name: Issue and PR comment commands

permissions: {}

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: jpmcb/prow-github-actions@f4d01dd4b13f289014c23fe5a19878a2479cb35b  # v1.1.3
        with:
          prow-commands: '/assign
            /unassign
            /area
            /kind
            /priority
            /remove
            /close
            /reopen
            /lock
            /milestone
            /hold
            /cc
            /uncc'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
